
# test
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydeploy
    spec:
      containers:
      - image: rajendrait99/addressbook:1.0
        name: addressbook
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
status: {}
